# -*- ruby -*-

# DO NOT EDIT THIS FILE. Instead, edit Rakefile, and run `rake bundler:gemfile`.

source "https://rubygems.org/"


gem "minitest", "~>5.15", :group => [:development, :test]
gem "rake-compiler", "~>1.2.0", :group => [:development, :test]
gem "rake-compiler-dock", "~>1.2.1", :group => [:development, :test]
gem "mini_portile2", "~>2.8.0", :group => [:development, :test]
gem "hoe-bundler", "~>1.0", :group => [:development, :test]
gem "hoe-gemspec", "~>1.0", :group => [:development, :test]
gem "rdoc", ">=4.0", "<7", :group => [:development, :test]
gem "hoe", "~>3.23", :group => [:development, :test]

# vim: syntax=ruby
