# -*- ruby -*-

# DO NOT EDIT THIS FILE. Instead, edit Rakefile, and run `rake bundler:gemfile`.

source "https://rubygems.org/"


gem "minitest", "~>5.11", :group => [:development, :test]
gem "rake-compiler", "~>1.0", :group => [:development, :test]
gem "rake-compiler-dock", "~>0.6.0", :group => [:development, :test]
gem "mini_portile", "~>0.6.2", :group => [:development, :test]
gem "hoe-bundler", "~>1.0", :group => [:development, :test]
gem "hoe-gemspec", "~>1.0", :group => [:development, :test]
gem "rdoc", ">=4.0", "<6", :group => [:development, :test]
gem "hoe", "~>3.17", :group => [:development, :test]

# vim: syntax=ruby
